ocp-power-automation/ocs-upi-kvm

README.md
samples/dev-ocs.sh
samples/jenkins-ocs-psi.sh
scripts/create-ocp.sh
scripts/deploy-ocs-ci.sh
scripts/destroy-ocp.sh
scripts/helper/add-data-disks.sh
scripts/helper/check-health-cluster.sh
scripts/helper/create-cluster.sh
scripts/helper/parameters.sh
scripts/helper/set-passwordless-sudo.sh
scripts/helper/setup-kvm-host.sh
scripts/helper/virsh-cleanup.sh
scripts/setup-ocs-ci.sh
scripts/teardown-ocs-ci.sh
scripts/test-ocs-ci.sh

Sudo capability with passwordless access is required.
The project can be git cloned anywhere, but it should be
noted that the parent directory is assumed to be a workspace
where a lot of files are copied, including log files.  Many
of these files have value that transcend the project which is
just a tool to create a cluster with OCS.  This includes
cluster administration as the oc command and kubeconfig
are copied into the workspace.
Assuming the ocs-upi-kvm project is located at:
~/workspace/ocs-upi-kvm
One would invoke oc like this:
export KUBECONFIG=~/workspace/auth/kubeconfig
~/workspace/bin/oc get nodes
Non-root users must use sudo to see VMs with virsh:
sudo virsh list --all

Allow non-root users to run this project

---

scripts/helper/create-cluster.sh

... As opposed to other methods, to reset the ocp4-upi-kvm submodule.
Mainly, this avoids having to hardcode a branch name in this script,
allowing for easier testing in some workflows.
Signed-off-by: Zack Cerza <zack@redhat.com>

create-cluster.sh: Use git submodule deinit

---

scripts/helper/create-cluster.sh
scripts/helper/parameters.sh
scripts/helper/setup-kvm-host.sh

We were running multiple dnsmasq instances on the host, one of which
forwarded requests for the cluster domain to the other, which then
forwarded those requests to named on the bastion. The bastion is also
set up to forward requests to the host, creating a loop. During periods
of high activity, the dnsmasqs were getting overwhelmed, leading to
response times in the 2-5 second range. This change brings us back into
the ~1ms range.
Signed-off-by: Zack Cerza <zack@redhat.com>

Fix DNS overloading

---

scripts/create-ocp.sh
scripts/helper/parameters.sh
scripts/helper/setup-kvm-host.sh

Implement a generation count for code changes to the script kvm-setup-host.sh
which will be stored in the file ~/.kvm_setup after invoking invoking the
aforementioned setup script.
The generation count serves as a simple version number.  When a cluster is created,
the ~/.kvm_setup file is read to determine the generation count that was evident
when the script was last invoked.  If the installed generation count is less than
or equal to the internal value carried in the source code of the project, then
the setup script should be invoked.
Existing behavior is not impacted.  If the file ~/.kvm_setup doesn't exist, the
setup script is invoked.  If the content of the file is empty, the setup script
is invoked.  In both cases, the file will be generated with a generation count.
If the installed …

Automate the invocation kvm-setup-host.sh with codes changes

---

files/ocs-ci/powervs/ocpdr

ocpdr utility needs to set the new required number of nodes based
on the current count of worker nodes

Fix ocpdr to get current worker nodes count

---

samples/dev-ocs.sh
scripts/deploy-ocs-ci.sh
scripts/test-ocs-ci.sh

This will change the ApprovalStrategy of Subscription from Automatic to Manual which will prevent from causing issues in tier runs as now OCS CSV version is automatically getting upgraded.  

Adding manual_subscription_plan_approval.yaml in run-ci for ocs

---

files/ocs-ci/ocs-ci-03-skip4xtest.patch

It will skip some of the tests in tier4 that are failing as they are shutting down the network interface which in turn causes the worker nodes to be in NotReady state. Corresponding PR for this in ocs-ci : https://github.com/red-hat-storage/ocs-ci/pull/4090

Skipping some of the tests in tier4x

---

files/ocs-ci/ocs-ci-04-skipscaletest.patch

This patch will skip one of the scale test as we are not supporting 'add-capacity' feature. 

Skipping one of the scale test

---

files/ocs-ci/ocs-ci-01-strimzi.patch

Changing strimzi-operator repository to https://github.com/ocs-power-automation/strimzi-kafka-operator

Changing strimzi repo

---

files/ocs-ci/ocs-ci-06-skip-memoryleak.patch

Skipping Scale testcase which is failing due to this error-> Unexpected Behaviour : Memory Leak file not found
Issue : https://github.com/red-hat-storage/ocs-ci/issues/3523

Skip scale test which fails due to memoryLeak

---

files/ocs-ci/ocs-ci-08-objectstorage.patch
files/ocs-ci/ocs-ci-09-serviceformat.patch

This commit includes changes to mcg test cases for IBM COS object storage.
It also includes changes to service module with format changes.
From setup-ocs-ci run:
atchfiles=../../files/ocs-ci/ocs-ci-00-ripsaw.patch ../../files/ocs-ci/ocs-ci-01-strimzi.patch ../../files/ocs-ci/ocs-ci-02-skip4xtest.patch ../../files/ocs-ci/ocs-ci-03-skipscaletest.patch ../../files/ocs-ci/ocs-ci-04-addcapacity-skip.patch ../../files/ocs-ci/ocs-ci-05-skip-memoryleak.patch ../../files/ocs-ci/ocs-ci-06-cpulimits.patch ../../files/ocs-ci/ocs-ci-07-optionaloperators.patch ../../files/ocs-ci/ocs-ci-08-objectstorage.patch ../../files/ocs-ci/ocs-ci-09-service.patch …

Objct storage and service patches

---

scripts/helper/kvm/virsh-cleanup.sh

The steps in "Delete storage volumes" loop requires the storage pool to be active. Added code to check for status, and if the pool is inactive, go ahead with deletion.

undefine storage pool if status is inactive

---

files/ocs-ci/ocs-ci-10-drain.patch

This patch adds --timeout=1810s to oc adm drain command
Without this change, ocs-ci/run-ci crashes while executing
drain command.

Add patch to help oc drain to work

---

files/ocs-ci/ocs-ci-01-strimzi.patch

PR includes following changes:
- Eliminate use of cloned repo and use the strimzi-kafka-operator's master branch as per ocs-ci. 
- Use ppc64le-based built images for Strimzi

Use strimzi-kafka-operator master branch

---

scripts/deploy-ocs-ci.sh

`monitoring_enabled` and `persistent-monitoring` parameters need to be enabled during deployment for running prometheus tests. It creates the configmap cluster-monitoring-config with reconfigured storage class.

pass monitoring.yaml during deployment

---

files/ocs-ci/ocs-ci-06-check-sc-exists.patch

setup-ocs-ci.sh script execution results:
```
Nothing to do.
Complete!
~/sc-fix/ocs-upi-kvm/src/ocs-ci ~/sc-fix/ocs-upi-kvm/scripts
patchfiles=../../files/ocs-ci/ocs-ci-00-ripsaw.patch ../../files/ocs-ci/ocs-ci-01-strimzi.patch ../../files/ocs-ci/ocs-ci-02-skipscaletest.patch ../../files/ocs-ci/ocs-ci-03-addcapacity-skip.patch ../../files/ocs-ci/ocs-ci-04-skip-memoryleak.patch ../../files/ocs-ci/ocs-ci-05-drain.patch ../../files/ocs-ci/ocs-ci-06-check-sc-exists.patch
ls: cannot access '../../files/ocs-ci/powervs/ocs-ci-*[0-9][0-9]-*.patch': No such file or directory
Generating consolidated patch file /home/aditi/sc-fix/ocs-ci.patch from /home/aditi/sc-fix/ocs-upi-kvm/files/ocs-ci/
checking file ocs_ci/ocs/ripsaw.py
checking file …
```

Add patch for missing SC fix and rebase ocs-ci

---

scripts/test-ocs-ci.sh

In order to run all tier tests, removing `manage` decorator from run-ci commands of tier tests. As the manage marker stands for the tests written by manage team.

Removing manage decorator from run-ci

---

files/ocs-ci/ocs-ci-01-strimzi.patch

Strimzi repository has updated using kafka-bridge image from quay.io/strimzi/kafka-bridge:0.20.1 to quay.io/strimzi/kafka-bridge:0.20.2 (https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L85)
due to which our patch is not getting applied for kafka-bridge image and pod is failing with CrashLoopBackOff error as image is x86 only (quay.io/strimzi/kafka-bridge:0.20.2) .

Correcting strimzi patch for kafka-bridge image

---

files/ocs-ci/ocs-ci-03-addcapacity-skip.patch
files/ocs-ci/ocs-ci-04-skip-memoryleak.patch
files/ocs-ci/ocs-ci-05-drain.patch
files/ocs-ci/ocs-ci-06-check-sc-exists.patch

patchfiles=../../files/ocs-ci/ocs-ci-00-ripsaw.patch ../../files/ocs-ci/ocs-ci-01-strimzi.patch ../../files/ocs-ci/ocs-ci-02-skipscaletest.patch ../../files/ocs-ci/ocs-ci-03-addcapacity-skip.patch ../../files/ocs-ci/ocs-ci-04-skip-memoryleak.patch ../../files/ocs-ci/ocs-ci-05-drain.patch ../../files/ocs-ci/ocs-ci-06-check-sc-exists.patch ../../files/ocs-ci/ocs-ci-07-kafka-drop.patch
Generating consolidated patch file /home/aditi/pr/rebase/ocs-ci.patch from /home/aditi/pr/rebase/ocs-upi-kvm/files/ocs-ci/
checking file ocs_ci/ocs/ripsaw.py
checking file …

ocs-ci rebase

---

files/ocs-ci/ocs-ci-01-strimzi.patch

unable to run setup-ocs-ci.sh script. It failed with error:
```
Generating consolidated patch file /root/ocs-ci.patch from /root/ocs-upi-kvm/files/ocs-ci/
WARNING: Failed to patch ocs-ci.  Has git submodule ocs-ci HEAD changed?
patch: **** malformed patch at line 66:  
```
This PR corrects the line numbers in the strimzi patch

fixing strimzi patch incorrect line numbers

---

files/ocs-ci/ocs-ci-02-skipscaletest.patch
files/ocs-ci/ocs-ci-03-addcapacity-skip.patch
files/ocs-ci/ocs-ci-06-check-sc-exists.patch

setup-ocs-ci.sh script results:
Generating consolidated patch file /home/aditi/rebase-3/ocs-ci.patch from /home/aditi/rebase-3/ocs-upi-kvm/files/ocs-ci/
checking file tests/e2e/registry/test_registry_by_increasing_num_of_image_registry_pods.py
checking file tests/e2e/registry/test_registry_pod_respin.py
checking file tests/e2e/registry/test_registry_pull_and_push_images_to_registry.py
checking file tests/e2e/registry/test_registry_reboot_node.py
checking file …

ocs-ci rebase and Adding patch to skip 2 tests

---

files/ocs-ci/ocs-ci-08-nodename-validation.patch

Resolving validation error which arose due to change in the naming convention of node names in ocp4-upi-powervs

Adding patch for nodename validation in ocs-ci

---

files/ocs-ci/ocs-ci-01-strimzi.patch

Updating strimzi-kafka-bridge image as it has changed in the upstream strimzi-kafka github repository : https://github.com/strimzi/strimzi-kafka-operator/blob/main/packaging/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L85
Signed-off-by: root <aaruniagg@gmail.com>

Updating kafka-bridge image

---

files/ocs-ci/ocs-ci-01-strimzi.patch

the strimzi-kafka-bridge image got updated to `quay.io/strimzi/kafka-bridge:0.21.3` in upstream. 
Hence updating the patch. 

kafka-bridge-image update

---

files/ocs-ci/ocs-ci-03-addcapacity-skip.patch
files/ocs-ci/ocs-ci-06-check-sc-exists.patch

Generating consolidated patch file /home/aditi/pr/ocs-ci.patch from /home/aditi/pr/ocs-upi-kvm/files/ocs-ci/
checking file tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
checking file tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
checking file …

rebased ocs-ci

---

samples/upgrade-ocs.sh
scripts/debug-ceph-pods.sh

After Upgrading OCS from one version to another, the supplemental config file needs to be updated for running tier1 test cases. 
Hence updating `ocs_version` under ENV section in the config file.
Also, In order to execute tier tests, we need to add `ocs_csv_channel` in the config file. 
Correcting following command in scripts/debug-ceph-pods.sh as it will not work for ocs_version > 4.9
`OCS_VERSION=oc get csv $ocs_operator -o jsonpath={.spec.version} | cut -c1-3` 

Updating upgrade script

---

files/ocs-ci/ocs-ci-01-strimzi.patch

Upstream strimzi-kafka git repository added new image `quay.io/strimzi/kafka:latest-kafka-3.0.1` due to which our tier1 test case was failing. Hence updating our strimzi patchfile. 

Updating strimzi patch with new image

---

files/ocs-ci/ocs-ci-01-strimzi.patch

New image `quay.io/strimzi/kafka:latest-kafka-3.1.1` is added in the upstream strimzi-kafka repository and the following two images are removed from the upstream repository: `quay.io/strimzi/kafka:latest-kafka-3.0.0` and `quay.io/strimzi/kafka:latest-kafka-3.0.1` . Hence updating the patch. 

Updating strimzi image

---

scripts/run-fio.sh

From ODF4.9 onwards, `max_avail_GiB` and `max_avail_unit` should be 10th and 11th field respectively. 
```
[root@rdr-aditi411-sao01-bastion-0 ~]# oc -n openshift-storage rsh rook-ceph-tools-7cf4d75b98-krppk ceph df | grep ocs-storagecluster-cephblockpool
ocs-storagecluster-cephblockpool                        1   32  338 MiB      137  1013 MiB   0.08    424 GiB
```
Also, 
```
[root@rdr-aditi411-sao01-bastion-0 scripts]# ocs_operator=`oc get csv | grep ocs-operator | awk {'print $1'}`
[root@rdr-aditi411-sao01-bastion-0 scripts]# ocs_version=`oc get csv $ocs_operator -n openshift-storage -o jsonpath={.spec.version} | cut -c1-3`
[root@rdr-aditi411-sao01-bastion-0 scripts]# echo $ocs_version
4.1
[root@rdr-aditi411-sao01-bastion-0 ~]# OCS_VERSION=`oc get csv $ocs_operator -o …
```

Updating ocs_version and conditional statement for 4.11

---

files/ocs-ci/ocs-ci-13-gevent.patch

Modified gevent version in setup.py script in ocs-ci as the current gevent version 20.9.0 installation is failing and its blocking nx124 jobs

modified gevent version from 20.9.0 to 21.12.0

---

scripts/setup-ocs-ci.sh

The setup script fails to install scipy version 1.8.1 due to setuptools version==65.
Related issue: https://github.com/numpy/numpy/issues/22135 
Hence degrading the setuptools version to `63.2.0`

Fixing scipy==1.8.1 installation error

---

files/ocs-ci/ocs-ci-12-lso-pod-security.patch

This patch adds label to `openshift-local-storage` namespace for PodSecurity Admission. 
Signed-off-by: root <aaruniagg@gmail.com>

Adding patch for lso namespace podSecurity fix

---

files/ocs-ci/ocs-ci-09-podname-change.patch

ODF deployment was failing due to following error: 
```
File "/root/venv/lib64/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
exec(co, module.__dict__)
File "/root/ocs-upi-kvm/src/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 31, in <module>
from ocs_ci.ocs.cluster import check_clusters
File "/root/ocs-upi-kvm/src/ocs-ci/ocs_ci/ocs/cluster.py", line 22, in <module>
import ocs_ci.ocs.resources.pod as pod
File "/root/ocs-upi-kvm/src/ocs-ci/ocs_ci/ocs/resources/pod.py", line 1771
ocs_version = version.get_semantic_ocs_version_from_config()
^
IndentationError: unexpected indent
```
Because indentation was incorrect in ocs-upi-kvm/src/ocs-ci/ocs_ci/ocs/resources/pod.py after applying the patch. 
Hence updated the patch with proper indentation. …

correcting indentation in one of the patch

---

files/ocs-ci/ocs-ci-12-skip-known-failures.patch
files/ocs-ci/ocs-ci-13-increase-timeout.patch

Adding patches for skipping known failures and increasing timeout for one of the tier2 testcase (tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py::TestCloneWhenFull::test_clone_when_full)

adding patch for skipping known failures

---

files/ocs-ci/ocs-ci-01-strimzi.patch

Removing own built images as multi-arch images are now available in https://quay.io/organization/strimzi

Removing own build images from strimzi patch for 4.13

---

files/ocs-ci/ocs-ci-01-strimzi.patch

Updating strimzi patch for 4.12 as multi-arch strimzi images are now available in the https://quay.io/strimzi/ repository.

Removing own build images from strimzi patch for 4.12

---

files/ocs-ci/ocs-ci-03-addcapacity-skip.patch
files/ocs-ci/ocs-ci-05-drain.patch
files/ocs-ci/ocs-ci-06-check-sc-exists.patch
files/ocs-ci/ocs-ci-08-nodename-validation.patch
files/ocs-ci/ocs-ci-09-podname-change.patch
files/ocs-ci/ocs-ci-12-skip-known-failures.patch
files/ocs-ci/ocs-ci-13-increase-timeout.patch
files/ocs-ci/ocs-ci-14-apply-icsp.patch
files/ocs-ci/ocs-ci-17-scipy-fix.patch
samples/cron/test-cron-ocs.sh
samples/dev-ocs-fio.sh
samples/dev-ocs-perf.sh
samples/dev-ocs.sh
samples/powervs-test-ocs.sh
samples/test-ocs-perf.sh
samples/test-ocs.sh
scripts/helper/create-cluster.sh
scripts/helper/parameters.sh
scripts/run-fio.sh

**Output setup script before applying patch**
```
Generating consolidated patch file /root/shilpi-rebase/ocs-ci.patch from /root/shilpi-rebase/ocs-upi-kvm/files/ocs-ci/
checking file tests/cross_functional/scale/test_scale_osds_fill_75%_reboot_workers.py
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
Hunk #2 succeeded at 48 (offset 2 lines).
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
checking file …
```

Rebasing ocs-ci 4.17 Changed the required patch files

---

files/ocs-ci/ocs-ci-00-ripsaw.patch
files/ocs-ci/ocs-ci-01-strimzi.patch
files/ocs-ci/ocs-ci-02-skipscaletest.patch
files/ocs-ci/ocs-ci-03-addcapacity-skip.patch
files/ocs-ci/ocs-ci-04-skip-memoryleak.patch
files/ocs-ci/ocs-ci-05-drain.patch
files/ocs-ci/ocs-ci-06-check-sc-exists.patch
files/ocs-ci/ocs-ci-08-nodename-validation.patch
files/ocs-ci/ocs-ci-12-skip-known-failures.patch
files/ocs-ci/ocs-ci-13-increase-timeout.patch
files/ocs-ci/ocs-ci-14-apply-icsp.patch
files/ocs-ci/ocs-ci-15-log-rotate.patch
files/ocs-ci/ocs-ci-17-node-mantainance-skip.patch
files/ocs-ci/ocs-ci-18-test-replica-skip.patch

**Setup script after changing patch files**
Created new patch file for skipping test files/ocs-ci/ocs-ci-18-test-replica-skip.patch due to issue https://github.com/red-hat-storage/ocs-ci/issues/10706
```
~/ocs-upi-kvm/src/ocs-ci ~/ocs-upi-kvm/scripts
patchfiles=../../files/ocs-ci/ocs-ci-00-ripsaw.patch ../../files/ocs-ci/ocs-ci-01-strimzi.patch ../../files/ocs-ci/ocs-ci-02-skipscaletest.patch ../../files/ocs-ci/ocs-ci-03-addcapacity-skip.patch ../../files/ocs-ci/ocs-ci-04-skip-memoryleak.patch ../../files/ocs-ci/ocs-ci-05-drain.patch ../../files/ocs-ci/ocs-ci-06-check-sc-exists.patch ../../files/ocs-ci/ocs-ci-07-kafka-drop.patch ../../files/ocs-ci/ocs-ci-08-nodename-validation.patch ../../files/ocs-ci/ocs-ci-10-logwriter.patch ../../files/ocs-ci/ocs-ci-11-lso-pod-security.patch …
```

Made changes for 4.18 branch

---

files/ocs-ci/ocs-ci-19-rook-ceph-plugin.patch
scripts/helper/rook-ceph-plugin.sh

These changes will install kubectl-rook-ceph plugin and also updates ocs-ci code for using installed plugin.
These changes are required as 2 of the tier2 tests (`tests/cross_functional/kcs/test_maintenance_pod.py::TestMaintenancePod::test_maintenance_pod_for_osd` ; 
`tests/cross_functional/kcs/test_maintenance_pod.py::TestMaintenancePod::test_maintenance_pod_for_mons`) are failing without these changes.

Adding script for installing kubectl-rook-ceph plugin

---

scripts/helper/rook-ceph-plugin.sh

jenkins job is failing without this as openshift-storage NS doesn't exist just after creating OCP cluster.

add else statement after checking namespace

---

scripts/helper/rook-ceph-plugin.sh

This will fix jenkins job as rook-ceph-plugin.sh script is terminating at `oc get namespace/openshift-storage > /dev/null 2>&1` as set -e is present at the top of the script.

Fixing jenkins job

---

files/ocs-ci/ocs-ci-19-rook-ceph-plugin.patch
scripts/helper/rook-ceph-plugin.sh

Copying kubectl-rook-ceph binary into bin while installing it, instead of  copying it while running tests.

copying kubectl-rook-ceph-binary to bin

---

files/ocs-ci/ocs-ci-03-addcapacity-skip.patch
files/ocs-ci/ocs-ci-05-drain.patch
files/ocs-ci/ocs-ci-06-check-sc-exists.patch
files/ocs-ci/ocs-ci-08-nodename-validation.patch
files/ocs-ci/ocs-ci-09-scipy-numpy.patch
files/ocs-ci/ocs-ci-12-skip-known-failures.patch
samples/cron/test-cron-ocs.sh
samples/dev-ocs-fio.sh
samples/dev-ocs-perf.sh
samples/dev-ocs.sh
samples/powervs-test-ocs.sh
samples/test-ocs-perf.sh
samples/test-ocs.sh
samples/upgrade-ocs.sh
scripts/helper/create-cluster.sh
scripts/helper/parameters.sh

Setup script output
```
patchfiles=../../files/ocs-ci/ocs-ci-00-ripsaw.patch ../../files/ocs-ci/ocs-ci-01-strimzi.patch ../../files/ocs-ci/ocs-ci-02-skipscaletest.patch ../../files/ocs-ci/ocs-ci-03-addcapacity-skip.patch ../../files/ocs-ci/ocs-ci-04-skip-memoryleak.patch ../../files/ocs-ci/ocs-ci-05-drain.patch ../../files/ocs-ci/ocs-ci-06-check-sc-exists.patch ../../files/ocs-ci/ocs-ci-07-kafka-drop.patch ../../files/ocs-ci/ocs-ci-08-nodename-validation.patch ../../files/ocs-ci/ocs-ci-09-scypi-numpy.patch ../../files/ocs-ci/ocs-ci-10-logwriter.patch ../../files/ocs-ci/ocs-ci-11-lso-pod-security.patch ../../files/ocs-ci/ocs-ci-12-skip-known-failures.patch ../../files/ocs-ci/ocs-ci-13-increase-timeout.patch ../../files/ocs-ci/ocs-ci-14-apply-icsp.patch …
```

Making changes for 4.19 rebase

---

files/ocs-ci/ocs-ci-17-setup.patch
files/ocs-ci/ocs-ci-18-test_nodes_maintenance.patch
scripts/setup-ocs-ci.sh

```
Generating consolidated patch file /root/ocs-ci.patch from /root/ocs-upi-kvm/files/ocs-ci/
checking file tests/cross_functional/scale/test_scale_osds_fill_75%_reboot_workers.py
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
checking file …
```

Added changes for running zstream jobs for 4.16

---

files/ocs-ci/ocs-ci-20-setup.patch

Setup Logs
```
Generating consolidated patch file /root/ocs-ci.patch from /root/ocs-upi-kvm/files/ocs-ci/
checking file tests/cross_functional/scale/test_scale_osds_fill_75%_reboot_workers.py
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py …
```

4.18 changes for zstream
