ocp-power-automation/ocs-upi-kvm

scripts/test-ocs-ci.sh
Signed-off-by: Luke Browning <lukebrowning@us.ibm.com>
=> Minor cleanup for test-ocs-ci.sh

files/ocp4-upi-kvm.legacy.patch, files/ocp4-upi-kvm.patch, scripts/helper/create-cluster.sh
Signed-off-by: Luke Browning <lukebrowning@us.ibm.com>
=> Use the input parameter bastion image name instead of soft link

README.md, files/ocp4-upi-kvm.legacy.patch, files/ocp4-upi-kvm.patch, scripts/create-ocp.sh, scripts/helper/create-cluster.sh, scripts/helper/parameters.sh
as opposed to RH user id and password.
RH user id and password take precedence
Signed-off-by: Luke Browning <lukebrowning@us.ibm.com>
=> Add support for RH org and subscription key

scripts/helper/setup-kvm-host.sh
This will ensure any change in settings actually gets applied.
Signed-off-by: Zack Cerza <zack@redhat.com>
=> setup-kvm-host.sh: Restart haproxy

README.md, samples/test-chron-ocs.sh, scripts/helper/chron-ocs.sh
This change includes scripts to automate OCP/OCS/OCS-CI and also execute
tier X tests.
Signed-off-by: Sridhar Venkat <svenkat@MacBook-Pro-4.attlocal.net>
=> Add CHRONTAB automation to deploy OCS

files/kvm/haproxy.cfg
Signed-off-by: Ron Edmark <redmark@redhat.com>
=> Update haproxy.cfg file with correct port number #24

files/ocs-ci/ocs-ci-01-strimzi.patch
Adding ocs-ci-01-strimzi.patch which involves all the image changes to multi-arch . 
=> Updating images to multi-arch for strimzi operator

files/ocs-ci/ocs-ci-02-noderestart.patch, scripts/helper/parameters.sh
=> Add remote ocs-ci capability.

files/kvm/site.tfvars.in
Trying again since #32 was closed (in error, I think).
=> Specify a recent commit for helpernode_tag

files/ocs-ci/ocs-ci-02-noderestart.patch, files/ocs-ci/ocs-ci-05-addcapacity-skip.patch
First patch is about ssh commandline, with -f parameter added.
Second patch is about skipping cluster_expansion tests.
=> ocs-ci patches

scripts/upgrade-ocs-ci.sh
Adding Upgrade script for OCS. This will also trigger pre/post upgrade tests.
Will check the script once OCS4.7.1 build will be available.
=> Upgrade script for OCS

samples/dev-ocs-fio.sh
Add ceph config commands in fio automation script. This will setup
the ceph envionment to recognize nvme/ssd storage.
=> Add ceph configuration for nvme/ssd storage

samples/cron/test-cron-ocs.sh, scripts/upgrade-ocs-ci.sh
Adding missing configuration file for upgrade and cleaning the script
And also adding ceph -s command in test-cron.sh as suggested by Sridhar
=> Minor changes and adding missing conf file in upgrade

scripts/upgrade-ocs-ci.sh
Adding missing config file for OCS subscription approval and appending date and time in logfile. 
=> adding missing config file in upgrade script

samples/upgrade-ocs.sh
Closing my previous PR #48 as it has conflicts and creating new one. 
=> adding e2e upgrade script

scripts/helper/powervs/parameters.sh
Updated RHCOS image to rhcos-48-07052021 for OCP 4.8
=> update RHCOS image for OCP 4.8

scripts/test-ocs-ci.sh
Resolves https://github.ibm.com/redstack-power/project-mgmt/issues/1778
=> Code changes to run prometheus related test cases

files/ocs-ci/ocs-ci-01-strimzi.patch, files/ocs-ci/ocs-ci-07-kafka-drop.patch, scripts/setup-ocs-ci.sh
Creating a patch for updating x86 specific kafdrop image to use ppc64le one.
=> adding patch for ppc64le kafka-drop image

scripts/helper/powervs/parameters.sh
Updating rhcos 4.7, 4.8 and 4.9 images. 
=> Updating rhcos images

files/ocs-ci/ocs-ci-01-strimzi.patch
Adding new tags (2.8.1 and 3.0.0) for kafka images as images got updated in upstream repository. 
=> Updating strimzi images with new tags

files/ocs-ci/ocs-ci-01-strimzi.patch, files/ocs-ci/ocs-ci-03-addcapacity-skip.patch, files/ocs-ci/ocs-ci-05-drain.patch, files/ocs-ci/ocs-ci-06-check-sc-exists.patch
Rebasing ocs-ci to the latest and modifying patches accordingly.
Signed-off-by: root <aaruniagg@gmail.com>
=> Rebasing ocs-ci

scripts/helper/powervm/parameters.sh
Deployed 4.10 OCP and ODF. Results updated here - https://github.ibm.com/redstack-power/project-mgmt/issues/2146
=> Adding powervm 4.10 support

samples/add-hmc-storage.sh
=> adding script to attach storage using hmc

files/ocs-ci/ocs-ci-01-strimzi.patch
=> modified strimzi patch to update kafka bridge tag

scripts/helper/create-cluster.sh, scripts/helper/powervs/parameters.sh
=> updated ocp client and rhcos images

samples/cron/test-cron-ocs.sh, samples/dev-ocs-fio.sh, samples/dev-ocs-perf.sh, samples/dev-ocs.sh, samples/powervs-test-ocs.sh, samples/test-ocs-perf.sh, samples/test-ocs.sh, scripts/helper/create-cluster.sh, scripts/helper/parameters.sh, scripts/helper/powervs/parameters.sh
OCP 4.11 deployment testing in progress. Please hold on merging this PR
=> adding 4.11 support for powervs

files/ocs-ci/ocs-ci-01-strimzi.patch, files/ocs-ci/ocs-ci-03-addcapacity-skip.patch, files/ocs-ci/ocs-ci-05-drain.patch, files/ocs-ci/ocs-ci-08-nodename-validation.patch, files/ocs-ci/ocs-ci-09-podname-change.patch, files/ocs-ci/ocs-ci-10-noobaa-scale.patch, files/ocs-ci/ocs-ci-12-rbd-spacereclaim.patch
=> rebased ocs-ci and added a patch for rbd space reclaim testcase

scripts/helper/create-cluster.sh, scripts/helper/powervs/parameters.sh
A new branch for OCP4.10 got created in the `ocp4-upi-powervs` repository. Hence updating the script with the same. 
=> Adding branch for ocp4.10 in powervs

scripts/helper/powervm/parameters.sh
=> Adding 4.11 support for powervm and kvm

scripts/helper/create-cluster.sh
Updating `OCP_RELEASE` to the latest stable OCP versions. 
=> Updating OCP_RELEASE to latest-stable versions

files/ocs-ci/ocs-ci-01-strimzi.patch
The new image got introduced in the upstream strimzi-kafka github repository. Hence updating the patch. 
=> updating strimzi patch with kafka--3.2.1

scripts/setup-ocs-ci.sh, scripts/test-ocs-ci.sh
Rerunning the failed test cases specified number of times
=> Rerun failed/errored/skipped testcases

files/ocs-ci/ocs-ci-01-strimzi.patch
Updating the patch with latest strimzi-kafka images. 
=> updating strimzi images to latest

scripts/helper/create-cluster.sh, scripts/helper/powervs/parameters.sh
Adding changes for OCP4.13 in create-cluster.sh script. 
=> adding changes for 4.13

files/ocs-ci/ocs-ci-03-addcapacity-skip.patch, files/ocs-ci/ocs-ci-06-check-sc-exists.patch, files/ocs-ci/ocs-ci-08-nodename-validation.patch, files/ocs-ci/ocs-ci-09-podname-change.patch, files/ocs-ci/ocs-ci-12-skip-known-failures.patch
=> rebasing ocs-ci submodule

scripts/helper/powervm/parameters.sh
updating rhcos and rhel images in powerVM script. 
=> 414 update

files/ocs-ci/ocs-ci-01-strimzi.patch, files/ocs-ci/ocs-ci-04-skip-memoryleak.patch, files/ocs-ci/ocs-ci-06-check-sc-exists.patch, files/ocs-ci/ocs-ci-09-podname-change.patch
=> Rebasing main branch

files/ocs-ci/ocs-ci-06-check-sc-exists.patch
Rebasing ocs-ci submodule for v4.13.0 branch of ocs-upi-kvm
=> rebasing 4.13 branch

files/ocs-ci/ocs-ci-06-check-sc-exists.patch, files/ocs-ci/ocs-ci-14-upgrade-icsp.patch
Adding patch for applying ICSP in upgrade jobs
=> adding patch for applying icsp in upgrade

files/ocs-ci/ocs-ci-01-strimzi.patch
Modifying strimzi patch with latest images. 
=> modifying strimzi patch for 4.13

files/ocs-ci/ocs-ci-03-addcapacity-skip.patch, files/ocs-ci/ocs-ci-06-check-sc-exists.patch, files/ocs-ci/ocs-ci-14-apply-icsp.patch, files/ocs-ci/ocs-ci-15-hpa-endpoint.patch
Rebasing ocs-ci submodule as it has fixes for some of the testcases
Creating a patch for fixing horizontalpodautoscaler name in openshift-storage namespace. 
=> adding patch for hpa endpoint testcase

files/ocs-ci/ocs-ci-01-strimzi.patch
Removing own built images as multi-arch images are now available in https://quay.io/organization/strimzi
=> Removing own build images from strimzi patch

files/ocs-ci/ocs-ci-02-skipscaletest.patch, files/ocs-ci/ocs-ci-03-addcapacity-skip.patch, files/ocs-ci/ocs-ci-04-skip-memoryleak.patch, files/ocs-ci/ocs-ci-05-drain.patch, files/ocs-ci/ocs-ci-06-check-sc-exists.patch, files/ocs-ci/ocs-ci-08-nodename-validation.patch, files/ocs-ci/ocs-ci-09-podname-change.patch, files/ocs-ci/ocs-ci-12-skip-known-failures.patch, files/ocs-ci/ocs-ci-13-increase-timeout.patch, files/ocs-ci/ocs-ci-15-log-rotate.patch, scripts/setup-ocs-ci.sh
Updated patch files and setup script for odf 4.16
=> Rebasing for 4.16 and Updated setup script

files/ocs-ci/ocs-ci-12-skip-known-failures.patch, samples/cron/test-cron-ocs.sh, samples/dev-ocs-fio.sh, samples/dev-ocs-perf.sh, samples/dev-ocs.sh, samples/powervs-test-ocs.sh, samples/test-ocs-perf.sh, samples/test-ocs.sh, scripts/helper/create-cluster.sh, scripts/helper/parameters.sh, scripts/run-fio.sh
=> Version change for ODF 4.16

scripts/setup-ocs-ci.sh
```
Generating consolidated patch file /root/ocs-ci.patch from /root/ocs-upi-kvm/files/ocs-ci/
checking file tests/cross_functional/scale/test_scale_osds_fill_75%_reboot_workers.py
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
checking file tests/functional/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
checking file tests/functional/z_cluster/cluster_expansion/test_delete_pod.py
checking file …
```
=> Update setup-ocs-ci.sh to point to latest version of python packages
